/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ghostmouse_GhostMouse */

#ifndef _Included_ghostmouse_GhostMouse
#define _Included_ghostmouse_GhostMouse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ghostmouse_GhostMouse
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ghostmouse_GhostMouse_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ghostmouse_GhostMouse
 * Method:    moveTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_ghostmouse_GhostMouse_moveTo
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     ghostmouse_GhostMouse
 * Method:    setCursorImage
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_ghostmouse_GhostMouse_setCursorImage
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     ghostmouse_GhostMouse
 * Method:    setTextImage
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_ghostmouse_GhostMouse_setTextImage
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     ghostmouse_GhostMouse
 * Method:    setTextOffset
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_ghostmouse_GhostMouse_setTextOffset
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     ghostmouse_GhostMouse
 * Method:    show
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ghostmouse_GhostMouse_show
  (JNIEnv *, jobject);

/*
 * Class:     ghostmouse_GhostMouse
 * Method:    hide
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ghostmouse_GhostMouse_hide
  (JNIEnv *, jobject);

/*
 * Class:     ghostmouse_GhostMouse
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ghostmouse_GhostMouse_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
